Docs: Gen maintenance fixes for September
rsksmart/devportal pull request #109
Opened 2024-09-12 15:39 UTC by owans

## What
- Add hackathon cheatsheet
- Update MetaMask page to remove ref to RPC API 

## Why
- Related to #102 
- Hackathon resources

## Refs
- [Task](https://rsklabs.atlassian.net/browse/DV-204?atlOrigin=eyJpIjoiZWZiN2MzZDZmMDljNGFmNDlkOTk3YzRhMzc2ZGIxMGQiLCJwIjoiaiJ9)

2024-09-12 19:58 UTC, ivegabr requested changes
made 2 changes

2024-09-12 19:58 UTC, ivegabr commented on docs/02-developers/02-requirements/index.md
> +- Supported solc version: `0.8.29`
```suggestion
- Supported solc version: `0.8.20`
```

2024-09-12 19:58 UTC, ivegabr commented on docs/04-resources/07-hackathon/index.md
> +This guide details the necessary hardware and software requirements for developing on the Rootstock blockchain. It includes setup instructions for essential tools such as Java, Node.js, Hardhat, and
```suggestion
This guide details the necessary hardware and software requirements for developing on the Rootstock blockchain. It includes setup instructions for essential tools such as Java, Node.js, Hardhat, and RSKj, ensuring developers have a clear path to prepare their environment for Rootstock projects, whether for local development, testing, or deployment. Download the [Hackathon Cheatsheet PDF Here](/rootstock-cheatsheet.pdf)
```

2024-09-13 10:22 UTC, owans commented
Changes implemented. Thanks @ivegabr

2024-09-13 14:57 UTC, ivegabr approved these changes
ok

2024-09-13 15:28 UTC, merged